[package]
name = "fantoccini"
version = "0.11.8"

description = "High-level API for programmatically interacting with web pages through WebDriver."
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/fantoccini"
homepage = "https://github.com/jonhoo/fantoccini"
repository = "https://github.com/jonhoo/fantoccini.git"

keywords = ["webdriver", "chromedriver", "geckodriver", "phantomjs", "automation"]
categories = ["api-bindings", "development-tools::testing", "web-programming::http-client"]

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/fantoccini" }
maintenance = { status = "looking-for-maintainer" }

[dependencies]
webdriver = "0.38.0"
url = "1.5.0"
serde = "1.0"
serde_json = "1.0"
futures = "0.1.14"
tokio = "0.1"
hyper = "0.12"
hyper-tls = "0.3"
cookie = { version = "0.11", features = ["percent-encode"] }
base64 = "0.9.1"
mime = "0.3.9"
http = "0.1"
